export const commandsPrefix = 'extension.';
// key = command, value = function name
export const commandsList = [
  'runScript',
  'launchHelp',
  'launchInfo',
  'debugMsgBox',
  'debugConsole',
  'compile',
  'check',
  'build',
  'tidy',
  'au3stripper',
  'addincludes',
  'launchKoda',
  'changeParams',
  'killScript',
  'killScriptOpened',
  'openInclude',
  'insertHeader',
  'restartScript',
  'debugRemove',
  'functionTraceAdd',
  'traceRemove',
];
